-- Book Loop v6: 거래함 및 수락 후 배송 정보 공유
-- Supabase SQL Editor에서 이 파일 전체를 한 번 실행하세요.

create table if not exists public.exchange_requests (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.profiles(id) on delete cascade,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  requested_book_id text not null,
  offered_book_id text not null,
  status text not null default 'pending'
    check (status in ('pending', 'accepted', 'rejected')),
  created_at timestamptz not null default now(),
  check (requester_id <> owner_id)
);

alter table public.exchange_requests enable row level security;

create unique index if not exists one_pending_request_per_book
on public.exchange_requests (requester_id, requested_book_id)
where status = 'pending';

create or replace function public.validate_exchange_request()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.books
    where id::text = new.requested_book_id
      and owner_id = new.owner_id
      and available_for_exchange = true
  ) then
    raise exception 'The requested book is not available for exchange.';
  end if;

  if not exists (
    select 1 from public.books
    where id::text = new.offered_book_id
      and owner_id = new.requester_id
      and available_for_exchange = true
  ) then
    raise exception 'The offered book is not available for exchange.';
  end if;

  return new;
end;
$$;

drop trigger if exists validate_exchange_request_trigger on public.exchange_requests;
create trigger validate_exchange_request_trigger
before insert on public.exchange_requests
for each row execute procedure public.validate_exchange_request();

create or replace function public.protect_exchange_request_fields()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.requester_id <> old.requester_id
    or new.owner_id <> old.owner_id
    or new.requested_book_id <> old.requested_book_id
    or new.offered_book_id <> old.offered_book_id
    or new.created_at <> old.created_at then
    raise exception 'Only the exchange request status can be changed.';
  end if;
  return new;
end;
$$;

drop trigger if exists protect_exchange_request_fields_trigger on public.exchange_requests;
create trigger protect_exchange_request_fields_trigger
before update on public.exchange_requests
for each row execute procedure public.protect_exchange_request_fields();

drop policy if exists "Participants can read exchange requests" on public.exchange_requests;
create policy "Participants can read exchange requests"
on public.exchange_requests for select
using (auth.uid() = requester_id or auth.uid() = owner_id);

drop policy if exists "Users can create exchange requests" on public.exchange_requests;
create policy "Users can create exchange requests"
on public.exchange_requests for insert
with check (
  auth.uid() = requester_id
  and requester_id <> owner_id
  and status = 'pending'
);

drop policy if exists "Owners can answer exchange requests" on public.exchange_requests;
create policy "Owners can answer exchange requests"
on public.exchange_requests for update
using (auth.uid() = owner_id and status = 'pending')
with check (auth.uid() = owner_id and status in ('accepted', 'rejected'));

drop policy if exists "Requesters can cancel exchange requests" on public.exchange_requests;
create policy "Requesters can cancel exchange requests"
on public.exchange_requests for delete
using (auth.uid() = requester_id and status = 'pending');

-- 배송지는 공개 프로필과 분리해 보관하고, 수락된 거래의 두 당사자만 조회할 수 있습니다.
create table if not exists public.exchange_shipping_details (
  request_id bigint not null references public.exchange_requests(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  recipient_name text not null check (char_length(recipient_name) between 1 and 50),
  phone text not null check (char_length(phone) between 1 and 30),
  postal_code text not null check (char_length(postal_code) between 1 and 20),
  address_line1 text not null check (char_length(address_line1) between 1 and 200),
  address_line2 text check (address_line2 is null or char_length(address_line2) <= 200),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (request_id, user_id)
);

alter table public.exchange_shipping_details enable row level security;

revoke all on public.exchange_shipping_details from anon;
grant select, insert, update on public.exchange_shipping_details to authenticated;

drop policy if exists "Accepted participants can read shipping details" on public.exchange_shipping_details;
create policy "Accepted participants can read shipping details"
on public.exchange_shipping_details for select
using (
  exists (
    select 1 from public.exchange_requests request
    where request.id = request_id
      and request.status = 'accepted'
      and auth.uid() in (request.requester_id, request.owner_id)
      and user_id in (request.requester_id, request.owner_id)
  )
);

drop policy if exists "Accepted participants can add own shipping details" on public.exchange_shipping_details;
create policy "Accepted participants can add own shipping details"
on public.exchange_shipping_details for insert
with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.exchange_requests request
    where request.id = request_id
      and request.status = 'accepted'
      and user_id in (request.requester_id, request.owner_id)
  )
);

drop policy if exists "Accepted participants can update own shipping details" on public.exchange_shipping_details;
create policy "Accepted participants can update own shipping details"
on public.exchange_shipping_details for update
using (auth.uid() = user_id)
with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.exchange_requests request
    where request.id = request_id
      and request.status = 'accepted'
      and user_id in (request.requester_id, request.owner_id)
  )
);
